# fly.toml app configuration file generated for dcn on 2023-09-22T13:54:01+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dcn"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  source="protocol_data"
  destination="/app/protocol_db"
