app = "autofollow"
primary_region = "sin"

[[vm]]
  size = "shared-cpu-1x"

[build]

[[services]]
  internal_port = 3500
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  
  [services.concurrency]
    hard_limit = 500
    soft_limit = 200
    type = "requests"
  
  [[services.ports]]
    handlers = ["http"]
    port = "80"

  [[services.ports]]
    handlers = ["tls", "http"]
    port = "443"

  [[services.tcp_checks]]
    interval = 10000
    timeout = 2000