name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy_rolodex:
    name: Deploy Rolodex
    runs-on: ubuntu-latest
    environment:
      name: prod-fly-io
      url: https://app-rolodex.shovel.company
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy Rolodex
        run: |
          cd packages/shovel-fs 
          npm link
          cd ../../apps/rolodex
          npm link shovel-fs
          cd ../..
          flyctl deploy --remote-only --ha=false --build-secret VITE_GOOGLE_CLIENT_ID=${{ secrets.VITE_GOOGLE_CLIENT_ID }} apps/rolodex
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  deploy_protocol:
    name: Deploy Protocol
    runs-on: ubuntu-latest
    environment:
      name: prod-fly-io
      url: https://testnet-protocol.shovel.company/
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy Protocol
        run: |
          ls
          cd protocol
          flyctl deploy --remote-only --ha=false
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_DCN }}
