name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy_rolodex:
    name: Deploy Rolodex
    runs-on: ubuntu-latest
    environment:
      name: prod-fly-io
      url: https://app-rolodex.shovel.company
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy Rolodex
        run: |
          flyctl deploy --remote-only --ha=false --build-secret VITE_GOOGLE_CLIENT_ID=${{ secrets.VITE_GOOGLE_CLIENT_ID }} --config apps/rolodex/fly.toml --dockerfile apps/rolodex/Dockerfile
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  deploy_protocol:
    name: Deploy Protocol
    runs-on: ubuntu-latest
    environment:
      name: prod-fly-io
      url: https://testnet-protocol.shovel.company/
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy Protocol
        run: |
          flyctl deploy --remote-only --ha=false  --config protocol/fly.toml --dockerfile protocol/Dockerfile
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_DCN }}
