name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy_rolodex:
    name: Deploy Rolodex
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy Rolodex
        run: |
          ls
          cd apps/rolodex
          flyctl deploy --remote-only --ha=false
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  deploy_protocol:
    name: Deploy Protocol
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy Protocol
        run: |
          ls
          cd protocol
          flyctl deploy --remote-only --ha=false
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN_DCN }}
